global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"] # Replace with your actual Postgres hostname if different
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "blackbox"
    static_configs:
      - targets: ["blackbox-exporter:9115"]
  - job_name: "elDoradoItems"
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: ["http://host.docker.internal:3001/ping"]
    static_configs:
      - targets: [""]
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: __address__
        replacement: blackbox-exporter:9115
rule_files:
  - "rules/*.yml"
